### DISCUSSION TITLE
How do i make walker open in full

### DISCUSSION THREAD

**Discussion by zspher** [abenz1267/walker#198] [Q&A]
![image](https://github.com/user-attachments/assets/f516d3b4-3576-45f7-980b-152ed7cbe8d7)
walker starts small. how do i make it expand at start? 
tested with `GTK_DEBUG=interactive walker`
the ff. are my configs

<details>
<summary>theme.json</summary>

```json
{
  "ui": {
    "fullscreen": true,
    "ignore_exclusive": true,
    "anchors": {
      "top": false,
      "bottom": false,
      "left": false,
      "right": false
    },
    "window": {
      "name": "window",
      "v_align": "center",
      "v_expand": false,
      "h_expand": false,
      "h_align": "center",
      "height": -1,
      "width": -1,
      "hide": false,
      "opacity": 1,
      "margins": {
        "bottom": 0,
        "start": 0,
        "end": 0,
        "top": 0
      },
      "box": {
        "name": "box",
        "v_align": "start",
        "v_expand": false,
        "h_expand": false,
        "h_align": "start",
        "height": -1,
        "width": 800,
        "hide": false,
        "opacity": 1,
        "margins": {
          "bottom": 0,
          "start": 0,
          "end": 0,
          "top": 0
        },
        "orientation": "vertical",
        "spacing": 0,
        "revert": false,
        "bar": {
          "name": "bar",
          "orientation": "vertical",
          "position": "start",
          "h_align": "fill",
          "h_expand": true,
          "spacing": 16,
          "entry": {
            "h_align": "start",
            "h_expand": false,
            "icon": {
              "v_align": "start",
              "v_expand": false,
              "h_expand": false,
              "h_align": "start",
              "height": -1,
              "width": -1,
              "hide": false,
              "opacity": 1,
              "margins": {
                "bottom": 0,
                "start": 0,
                "end": 0,
                "top": 0
              },
              "icon_size": "large",
              "pixel_size": -1,
              "theme": ""
            },
            "label": {
              "v_align": "fill",
              "v_expand": true,
              "y_align": 0.5,
              "margins": {
                "start": 4
              }
            }
          }
        },
        "search": {
          "name": "search",
          "v_align": "start",
          "v_expand": false,
          "h_expand": true,
          "h_align": "fill",
          "height": -1,
          "width": -1,
          "hide": false,
          "opacity": 1,
          "margins": {
            "bottom": 0,
            "start": 0,
            "end": 0,
            "top": 0
          },
          "prompt": {
            "name": "prompt",
            "text": "",
            "v_align": "start",
            "v_expand": false,
            "h_expand": false,
            "h_align": "start",
            "height": -1,
            "width": -1,
            "hide": false,
            "opacity": 1,
            "margins": {
              "bottom": 0,
              "start": 0,
              "end": 0,
              "top": 0
            },
            "justify": "start",
            "x_align": 0,
            "y_align": 0
          },
          "orientation": "horizontal",
          "spacing": 0,
          "revert": false,
          "input": {
            "name": "input",
            "v_align": "start",
            "v_expand": false,
            "h_expand": true,
            "h_align": "fill",
            "height": -1,
            "width": -1,
            "hide": false,
            "opacity": 1,
            "margins": {
              "bottom": 0,
              "start": 0,
              "end": 0,
              "top": 0
            },
            "icons": true
          },
          "spinner": {
            "name": "spinner",
            "v_align": "start",
            "v_expand": false,
            "h_expand": false,
            "h_align": "start",
            "height": -1,
            "width": -1,
            "hide": true,
            "opacity": 1,
            "margins": {
              "bottom": 0,
              "start": 0,
              "end": 0,
              "top": 0
            }
          }
        },
        "ai_scroll": {
          "name": "aiScroll",
          "margins": {
            "top": 8
          },
          "h_align": "fill",
          "v_align": "fill",
          "max_height": 300,
          "min_width": 800,
          "height": 300,
          "width": 800,
          "list": {
            "name": "aiList",
            "orientation": "vertical",
            "width": 800,
            "spacing": 10,
            "item": {
              "name": "aiItem",
              "h_align": "fill",
              "v_align": "fill",
              "x_align": 0.0,
              "y_align": 0.0,
              "wrap": true
            }
          }
        },
        "scroll": {
          "v_align": "start",
          "v_expand": false,
          "h_expand": false,
          "h_align": "start",
          "height": -1,
          "width": -1,
          "hide": false,
          "opacity": 1,
          "margins": {
            "bottom": 0,
            "start": 0,
            "end": 0,
            "top": 0
          },
          "overlay_scrolling": true,
          "h_scrollbar_policy": "automatic",
          "v_scrollbar_policy": "automatic",
          "list": {
            "name": "list",
            "v_align": "start",
            "v_expand": false,
            "h_align": "fill",
            "h_expand": true,
            "height": -1,
            "hide": false,
            "opacity": 1,
            "placeholder": {
              "name": "listplaceholder",
              "h_align": "fill",
              "h_expand": true,
              "x_align": 0.5,
              "margins": {
                "bottom": 0,
                "start": 0,
                "end": 0,
                "top": 10
              }
            },
            "margins": {
              "bottom": 0,
              "start": 0,
              "end": 0,
              "top": 0
            },
            "orientation": "vertical",
            "min_height": 0,
            "min_width": 800,
            "max_height": 400,
            "max_width": 500,
            "width": 800,
            "grid": false,
            "always_show": false,
            "item": {
              "name": "item",
              "v_align": "start",
              "v_expand": false,
              "h_expand": true,
              "h_align": "fill",
              "height": -1,
              "width": -1,
              "hide": false,
              "opacity": 1,
              "margins": {
                "bottom": 0,
                "start": 0,
                "end": 0,
                "top": 0
              },
              "orientation": "horizontal",
              "spacing": 0,
              "revert": false,
              "activation_label": {
                "name": "activationlabel",
                "v_align": "center",
                "v_expand": false,
                "h_expand": false,
                "h_align": "center",
                "height": -1,
                "width": -1,
                "hide": false,
                "opacity": 1,
                "margins": {
                  "bottom": 0,
                  "start": 0,
                  "end": 0,
                  "top": 0
                },
                "justify": "start",
                "x_align": 0,
                "y_align": 0,
                "override": false,
                "hide_modifier": false
              },
              "icon": {
                "name": "icon",
                "v_align": "center",
                "v_expand": false,
                "h_expand": false,
                "h_align": "center",
                "height": -1,
                "width": -1,
                "hide": false,
                "opacity": 1,
                "margins": {
                  "bottom": 0,
                  "start": 0,
                  "end": 0,
                  "top": 0
                },
                "icon_size": "large",
                "pixel_size": -1,
                "theme": ""
              },
              "text": {
                "name": "text",
                "v_align": "fill",
                "v_expand": true,
                "h_expand": true,
                "h_align": "fill",
                "height": -1,
                "width": -1,
                "hide": false,
                "opacity": 1,
                "margins": {
                  "bottom": 0,
                  "start": 0,
                  "end": 0,
                  "top": 0
                },
                "orientation": "vertical",
                "spacing": 0,
                "revert": false,
                "label": {
                  "wrap": false,
                  "name": "label",
                  "v_align": "fill",
                  "v_expand": true,
                  "h_expand": true,
                  "h_align": "start",
                  "height": -1,
                  "width": -1,
                  "hide": false,
                  "opacity": 1,
                  "margins": {
                    "bottom": 0,
                    "start": 0,
                    "end": 0,
                    "top": 0
                  },
                  "justify": "start",
                  "x_align": 0,
                  "y_align": 0.5
                },
                "sub": {
                  "name": "sub",
                  "v_align": "start",
                  "v_expand": false,
                  "h_expand": false,
                  "h_align": "start",
                  "height": -1,
                  "width": -1,
                  "hide": false,
                  "opacity": 1,
                  "margins": {
                    "bottom": 0,
                    "start": 0,
                    "end": 0,
                    "top": 0
                  },
                  "wrap": false,
                  "justify": "start",
                  "x_align": 0,
                  "y_align": 0
                }
              }
            }
          }
        }
      }
    }
  }
}

```
</details>
<details>
<summary>theme.css</summary>

```css
#window,
#box,
#search,
#password,
#input,
#typeahead,
#spinner,
#list,
child,
scrollbar,
slider,
#item,
#text,
#label,
#sub,
#activationlabel {
  all: unset;
}

#window {
  background: none;
}

#box {
  background: #1e1e2e;
  padding: 16px;
  border-radius: 8px;
  border: 2px solid #cba6f7;
  box-shadow: none;
}

scrollbar {
  background: none;
  padding-left: 8px;
}

slider {
  min-width: 2px;
  background: #7f849c;
  opacity: 0.5;
}

#search {
}

#password,
#input,
#typeahead {
  background: #313244;
  background: none;
  box-shadow: none;
  border-radius: 0px;
  border-radius: 32px;
  color: #cdd6f4;
  padding-left: 12px;
  padding-right: 12px;
}

#input {
  background: none;
}

#input > *:first-child,
#typeahead > *:first-child {
  color: #7f849c;
  margin-right: 7px;
}

#input > *:last-child,
#typeahead > *:last-child {
  color: #7f849c;
}

#spinner {
}

#typeahead {
  color: #89b4fa;
}

#input placeholder {
  opacity: 0.5;
}

#list {
}

child {
  color: #cdd6f4;
  padding: 4px;
  border-top: 1px solid #313244;
}

child:selected,
child:hover {
  border-radius: 8px;
  background: #313244;
  box-shadow: none;
  color: #cdd6f4;
}
child:selected + child,
child:hover + child,
child:first-child {
  border-top: none;
}

#item {
}

#icon {
}

#text {
}

#label {
  font-weight: bold;
  color: #cdd6f4;
}

#sub {
  opacity: 0.5;
  color: #cdd6f4;
}

#activationlabel {
  opacity: 0.5;
  padding-right: 4px;
}

.activation #activationlabel {
  font-weight: bold;
  color: #89b4fa;
  opacity: 1;
}

.activation #text,
.activation #icon,
.activation #search {
}

```
</details>
