### DISCUSSION TITLE
Plugin/Script for bitwarden CLI password copy to clipboard

### DISCUSSION THREAD

**Discussion by SHU-red** [abenz1267/walker#322] [Q&A] [answered]
Hi there,
trying to keep it quick and simple:

- Using bitwarden-plugin for chrome and firefox &rarr; nice!
- But leaning towards qutebrowser (no plugins) &rarr; userscript available but password information can be seen in debug log (https://github.com/qutebrowser/qutebrowser/blob/main/misc/userscripts/qute-bitwarden)

Also using walker, i tried to find a plugin definition to utilize bitwarden-cli for copying passwords into the clipboard via: walker &rarr; bitwarden-cli

Has there anything been done yet?

Im a bit hesitant to give it a shot myself because im not sure if i will handle the sensible data in a good way and do not know much about walkers plugin system (yet)

So i thought ill come here and ask the pros if there is already something available

Thanks

**Comment by SHU-red** [comment]
Im trying to get it done step by step

Preconditions:
- `bw`-cli installed and logged in with `bw login`
- use bitwarden cli `bw unlock --raw` to store the session key in `BW_SESSION` &rarr; I for myself am doing this by configuring a function in fish to be able to be executed:
```bash
function bw-login
    set -Ux BW_SESSION (bw unlock --raw)
    echo "BW_SESSION set successfully"
end
```
- jq installed

After `bw list items` then works without additional password promt im ready to try to extract entries i need by checking entry name and uris for my search term, below for tests im searching for `portainer`

```bash
╰$ bw list items | jq --arg term "portainer" '
     map(select(
       (.name | ascii_downcase | test($term; "i")) or
       (.login.uris[]?.uri | ascii_downcase | test($term; "i"))
     )) | .[].name
   '
"Portainer"
"Portainer Local"
"Portainer TrueNAS"
"portainer_work"
```

As shown above i get back a list of names where my search term matches

Now (i think) ive got the problem that i have to squeeze all of this into either a string to have it in my walker `config.toml` or create a additional external script

My test plugin below seems to never give back a result, maybe because of the escaped quotes?

```toml
[[plugins]]
name = "bitwarden"
prefix = "b:"
src = "bw list items | jq --arg term \"$TERM\" 'map(select((.name | ascii_downcase | test($term; \"i\"))or(.login.uris[]?.uri | ascii_downcase | test($term; \"i\")))) | .[].name' | echo "
cmd = "bw list password %RESULT% | wl-copy"
```

I think:
- External would be more fitting beause of the size of the script?
- I would also have to think about something for the username or completely switch to not copying the result into clipboard but emulate what most of these plugins do: <username><tab><password>
- The returned json of `bw list items` can be very long, why i would like to store its result temporarily and only once and then on changing the search term, only re-execute the `jq`-part of it


Maybe someone more used to this could give me a hint?
Making this work would be damn awesome for me

**Comment by SHU-red** [comment]
This should be already the much more performant solution storing all bitwarden entries after typing `b:` in a tmp folder

On every keystroke then only `jq` has to re-evaluate the locally available file:

```toml
[[plugins]]
name = "bitwarden"
prefix = "b:"
src_once = "mkdir -p /tmp/walker/plugins/bitwarden && bw list items > /tmp/walker/plugins/bitwarden/items.json"
src = "cat /tmp/walker/plugins/bitwarden/items.json | jq --arg term \"$TERM\" 'map(select((.name | ascii_downcase | test($term; \"i\")) or (.login.uris[]?.uri | ascii_downcase | test($term; \"i\")))) | .[].name' | echo"
cmd = "bw list password %RESULT% | wl-copy"
```

**Comment by SHU-red** [comment]
OK, now with the script extracted separately

`config.toml`
```toml
[[plugins]]
name = "bitwarden"
prefix = "b:"
src_once = "mkdir -p /tmp/walker/plugins/bitwarden && bw list items > /tmp/walker/plugins/bitwarden/items.json"
src = "bash ~/.config/walker/plugins/bitwarden/bitwarden.sh %TERM%"
cmd = "bw list password %RESULT% | wl-copy"
```

`~/.config/walker/plugins/bitwarden/bitwarden.sh`
```bash
!@/bin/bash

cat /tmp/walker/plugins/bitwarden/items.json | jq --arg term "$@" '
     map(select(
       (.name | ascii_downcase | test($term; "i")) or
       (.login.uris[]?.uri | ascii_downcase | test($term; "i"))
     )) | .[].name
   '
```

By itsself the script works perfect, but in walker i do not get any result ...

```bash
bash ./plugins/bitwarden/bitwarden.sh portainer
./plugins/bitwarden/bitwarden.sh: line 1: !@/bin/bash: No such file or directory
"Portainer"
"Portainer Local"
"Portainer TrueNAS"
"portainer_work"
```

Almost there!

**Comment by SHU-red** [comment]
OK .... seems that `src` and `src_once` can not be used similarly

@abenz1267 , do you think this could be a feature having both `src` and `src_once` available for plugins and prioritizing `src_once` blocking `src` until ready

This could be used for same use-cases like mine

**Comment by SHU-red** [comment, marked as answer]
OK, below now a first (i think relatively good working solution)

- install `bw` and login via `bw-login`
- unlock bitwarden `bw unlock` and store key in `BW_SESSION` variable
- `bw list items` should not need a password

Add this to `config.toml`
```toml
[[plugins]]
name = "bitwarden"
prefix = "b:"
# src_once = "mkdir -p /tmp/walker/plugins/bitwarden && bw list items > /tmp/walker/plugins/bitwarden/items.json"
src = "bash ~/.config/walker/plugins/bitwarden/bitwarden_src.sh %TERM%"
cmd = "bash ~/.config/walker/plugins/bitwarden/bitwarden_cmd.sh %RESULT%"
```

Create `~/.config/walker/plugins/bitwarden/bitwarden_src.sh`
```bash
#!/bin/bash

# Check if the file is older than 10 minutes or doesn't exist
if [[ ! -f /tmp/walker/plugins/bitwarden/items.json ]] || [[ $(find /tmp/walker/plugins/bitwarden/items.json -mmin +10) ]]; then
  mkdir -p /tmp/walker/plugins/bitwarden

  # Recursively remove all "password" keys from anywhere in the JSON and save
  bw list items | jq 'walk(
    if type == "object" then
      del(.password)
    else
      .
    end
  )' > /tmp/walker/plugins/bitwarden/items.json
fi

term="$@"

if [[ -z "$term" ]]; then
  jq_filter='.[]?.name'
else
  jq_filter='
    map(select(
      (.name // "" | ascii_downcase | contains($term)) or
      (any(.login.uris[]?.uri; . // "" | ascii_downcase | contains($term)))
    )) | .[].name
  '
fi

jq -r --arg term "$(echo "$term" | tr '[:upper:]' '[:lower:]')" "$jq_filter" /tmp/walker/plugins/bitwarden/items.json | sort -u

```

Create `~/.config/walker/plugins/bitwarden/bitwarden_cmd.sh`
```bash
#!/bin/bash

RESULT="$1"

if [[ -z "$RESULT" ]]; then
  echo "Usage: $0 <search_string>"
  exit 1
fi

ID=$(jq -r --arg res "$RESULT" '.[] | select(.name == $res) | .id' /tmp/walker/plugins/bitwarden/items.json)

if [[ -z "$ID" ]]; then
  echo "No matching item found for '$RESULT'"
  exit 2
fi

bw get password "$ID" | wl-copy
echo "Password copied to clipboard for item '$RESULT'"
```

- I "hacked" my current guess that `src` and `src_once` can not be used both &rarr; Therefor i just check if items.json is not older than 10 minutes to execute `bw list items` only once for a current search
- This only copies the password to the clipboard, in the future could also provide username and/or simulates typing to sort of "auto fill forms"

I hope this helps someone

Due to the fact that this is not perfect yet im very open to input

DISCLAIMER: not being good at jq and bash i used AI to speed up things a little bit ... so think twice if you use this stuff handling your passwords :laughing:
