### DISCUSSION TITLE
How to make image preview in clipboard module larger?

### DISCUSSION THREAD

**Discussion by youyoumu** [abenz1267/walker#330] [Q&A]
![image](https://github.com/user-attachments/assets/c2662f07-c0fd-4604-bb9d-d3398e84be50)

i have tried changing `image_height` value from 5 to 600, nothing happened.
```toml
[builtins.clipboard]
always_put_new_on_top = true
exec = "wl-copy"
weight = 5
name = "clipboard"
avoid_line_breaks = true
placeholder = "Clipboard"
image_height = 300 # this doesn't work
max_entries = 50
switcher_only = true
```
