### DISCUSSION TITLE
How do I add space between magnifying glass icon and input?

### DISCUSSION THREAD

**Discussion by omnigenous** [abenz1267/walker#75] [Q&A] [answered]
![2024-07-23_17-36-53](https://github.com/user-attachments/assets/b73d49f3-433a-4a2a-b841-6c023f99cbe7)

I know you can:

```css
#search placeholder {
  padding-left: 50px;
}
```

But that only affects placeholder not input (where cursor is) as expected.

**Comment by abenz1267** [comment, marked as answer]
```css
#search image:first-child {
  padding-right: 20px;
}
```
