### ISSUE TITLE
[Calculator] not working

### ISSUE THREAD

**Issue by RichardFevrier** [abenz1267/walker#131]
Could not make calculator working.

`version: 0.7.7`

`libqalculate` & `qalc` installed.

`~/.config/walker/config.yaml`

```
activation_mode:
    disabled: true
builtins:
    applications:
        actions: false
```

Started like so:
`walker --gapplication-service`
`walker --modules applications,calculator`

![Screenshot from 2024-09-25 12-13-19](https://github.com/user-attachments/assets/82c0a77d-6665-46e2-8ec2-a4b125b49afc)
