### ISSUE TITLE
Ctrl+J and Ctrl+K navigation not working even with activation mode disabled

### ISSUE THREAD

**Issue by Lau-San** [abenz1267/walker#169]
**Describe the bug**
`Ctrl+J` and `Ctrl+K` keybindings are doing nothing with activation mode disabled.

**Version**
0.10.3

**Minimal Config**
```json
{
    "activation_mode": {
        "disabled": true
    }
}

```

**To Reproduce**
- Disable activation mode with configuration shown above.
- Launch Walker
- Try to use `Ctrl+J` and `Ctrl+K` to go to next and previous entries

**Expected behavior**
- `Ctrl+J` should navigate to the next entry
- `Ctrl+K` should navigate to the previous entry

**Screenshots**
Moving with arrow keys:

https://github.com/user-attachments/assets/cab1a575-0aee-4054-8393-7a9a6a12177e

Trying to move with `Ctrl+J` and `Ctrl+K` (Nothing happens):

https://github.com/user-attachments/assets/76b86164-e82a-4f03-85b5-1f2191467703

**Desktop**

- EndeavourOS
- Hyprland

**Additional context**

[config.json](https://github.com/user-attachments/files/17962695/config.json)

This exact config was working fine before I updated Walker, and I don't see a reacon why it shouldn't work now.

**Comment by abenz1267** [comment]
That's because you need:

```json
{
  "activation_mode": {
    "disabled": true
  },
  "list": {
    "keyboard_scroll_style": "vim"
  }
}
```

It defaults to `emacs` with `ctrl+n`/`ctrl+p`.

**Comment by noahfraiture** [comment]
Hello, I tried exactly that but I can't make it work. My config is as simple as 
```
{
  "activation_mode": {
    "disabled": true
  },
  "list": {
    "keyboard_scroll_style": "vim"
  }
}
```
But it doesn't work. Do you know why ?

**Comment by abenz1267** [comment]
The keybinds have been made fully customizable some time ago, so `"keyboard_scroll_style": "vim"` is not even a thing anymore.

What i use:

```toml
[keys]
accept_typeahead = ["right"]
next = ["ctrl j", "down"]
prev = ["ctrl k", "up"]
```

**Comment by abenz1267** [comment]
for completion: this is all default keybinds

```toml
[keys]
accept_typeahead = ["tab"]
trigger_labels = "lalt"
next = ["down"]
prev = ["up"]
close = ["esc"]
remove_from_history = ["shift backspace"]
resume_query = ["ctrl r"]
toggle_exact_search = ["ctrl m"]
```
