### ISSUE TITLE
can't map shift tab

### ISSUE THREAD

**Issue by stepanzak** [abenz1267/walker#197]
**Describe the bug**
There's an undocumented keymap shift-tab that skips to the very last item. Binding anything to shift tab does nothing.

**Version**
0.11.2

**Minimal Config**
with no/default config, shift tab skips to the last item.

With `config.yaml` being this:
```yaml
keys:
  prev:
    - shift tab
    - up
    - alt tab
    - ctrl tab
```
every listed keymap selects the previous item except for shift tab. That still selects the last item.

**Desktop**

- EndeavourOS (Arch)
- Niri
