### ISSUE TITLE
Change size and location of walker window

### ISSUE THREAD

**Issue by parasbhanot** [abenz1267/walker#221]
I'm trying to change the launch position and size of the Walker application, but I can't find any relevant settings in the default config.toml file to achieve this. It would be great if I could modify these parameters directly. I've attempted to use Hyprland window rules, but hyprprop doesn't even detect the default Walker window. However, when I set the window mode in the config.toml of Walker, I can detect the window name using hyprprop.

Is it possible to adjust the position and size of Walker using the config.toml file or any other configuration file? Specifically, I want to center Walker on my monitor.

Thanks!

**Comment by abenz1267** [comment]
Layout changes need to be done in the `<theme>.toml` (or json or yaml) of your theme.

The default theme will always be overwritten with the actual defaults of Walker, so modifying that makes no sense. You can just copy the default theme, rename it. And set `theme` in Walker. Best starting point for positioning would be `ui.anchors`.

**Comment by parasbhanot** [comment]
Thanks , i am able to change the size of  walker windows by changing ui.window.box --> width variable but still i cannot change the position of it by changing ui.anchors as these variables only accept boolean values .

**Comment by abenz1267** [comment]
That is correct. You'd use them to set the generic location of the window, so f.e. top left corner:

```toml
[ui.anchors]
bottom = false
left = true
right = false
top = true
```

You'd use `margins` to further adjust the position afterwards.

**Comment by abenz1267** [comment]
Oh wait. I totally missed that you use `as_window`. In that case nothing here helps you. The window position has to be set  by hyprland.

**Comment by abenz1267** [comment]
But you can do this in hyprland:

```
windowrulev2 = float, title:(walker)$
windowrulev2 = move 0 0, title:(walker)$
```

**Comment by parasbhanot** [comment]
windowrulev2 = float, title:(walker)$
windowrulev2 = move 0 0, title:(walker)$ i have tried it but it not working . i do not think hyprland is even detecting it as window as hyprprop is simply ignoring this . it is behaving like waybar and waybar is not window/surface so windows rules do not apply to it but [https://github.com/abenz1267/walker/discussions/112](url) layer rule affects the walker but unfortunately layer rules do not have move parameter

**Comment by abenz1267** [comment]
You need to set `as_window` to `true` if you want walker to act as a normal window.

**Comment by abenz1267** [comment]
But tbh i'm not sure why you'd want to even do that on hyprland. You can just position walker using the layout file.

Like.. why do you want to use it as a regular window?

**Comment by parasbhanot** [comment]
I want to position Waybar in the center of my monitor, similar to how applications like Fuzzel or Rofi are positioned by default .  

BY combining hypalnd window rules 

windowrulev2 = float, title:(walker)$
windowrulev2 = move 0 0, title:(walker)$

and setting as_window as false  has worked . 

Thanks. 

i wish i could change the position the walker from form the config.toml instead forcing it form hyprland config .

**Comment by abenz1267** [comment]
Uhm... you can simply adjust the positon by changing the layout my friend.

There's a `default.toml` file in `.config/walker/themes`. You can just copy that to `<you theme name>.toml`. Change whatever layout you wanna change. And set `theme = "<your theme name>"` in `config.toml`.

You don't need to position via hyprland at all.

**Comment by parasbhanot** [comment]
I attempted to implement a similar approach but couldn't quite figure out what specific changes were necessary to make it work within the default.toml theme file. 

My custom theme file looks like this 
```fish
.config/walker/themes 
cat mytheme.toml 
```

``` toml 

# My custom theme

[ui.anchors]
bottom = true
left = true
right = true
top = true

[ui.window]
h_align = "fill"
v_align = "fill"

[ui.window.box]
h_align = "center"
width = 650

[ui.window.box.bar]
orientation = "horizontal"
position = "end"

[ui.window.box.bar.entry]
h_align = "fill"
h_expand = true

[ui.window.box.bar.entry.icon]
h_align = "center"
h_expand = true
pixel_size = 24
theme = ""

[ui.window.box.margins]
top = 200

[ui.window.box.ai_scroll]
name = "aiScroll"
h_align = "fill"
v_align = "fill"
max_height = 300
min_width = 400
height = 300
width = 400

[ui.window.box.ai_scroll.margins]
top = 8

[ui.window.box.ai_scroll.list]
name = "aiList"
orientation = "vertical"
width = 400
spacing = 10

[ui.window.box.ai_scroll.list.item]
name = "aiItem"
h_align = "fill"
v_align = "fill"
x_align = 0
y_align = 0
wrap = true

[ui.window.box.scroll.list]
max_height = 300
max_width = 400
min_width = 400
width = 400

[ui.window.box.scroll.list.item.activation_label]
h_align = "fill"
v_align = "fill"
width = 20
x_align = 0.5
y_align = 0.5

[ui.window.box.scroll.list.item.icon]
pixel_size = 26
theme = ""

[ui.window.box.scroll.list.margins]
top = 8

[ui.window.box.search.prompt]
name = "prompt"
icon = "edit-find"
theme = ""
pixel_size = 18
h_align = "center"
v_align = "center"

[ui.window.box.search.clear]
name = "clear"
icon = "edit-clear"
theme = ""
pixel_size = 18
h_align = "center"
v_align = "center"

[ui.window.box.search.input]
h_align = "fill"
h_expand = true
icons = true

[ui.window.box.search.spinner]
hide = true

```

**Comment by abenz1267** [comment]
If you actually want it to be ALWAYS centered, which i don't recommend, because that means it'll also center the input if the list is empty, you just need to:

```toml
[ui.window.box.margins]
top = 0 // or just remove it
```

and 

```toml
[ui.window.box]
h_align = "center"
v_align = "center" // center vertically
```
