### ISSUE TITLE
Crash when moving mouse

### ISSUE THREAD

**Issue by lukasl-dev** [abenz1267/walker#240]
**Describe the bug**
Walker crashes as soon as I move my mouse within the window.

**Version**

`0.11.19` via `nixpkgs-unstable`

**Minimal Config**

Just the default config, nothing changed:

```toml
app_launch_prefix = ""
terminal_title_flag = ""
locale = ""
close_when_open = false
theme = "default"
monitor = ""
hotreload_theme = false
as_window = false
timeout = 0
disable_click_to_close = false
force_keyboard_focus = false

[keys]
accept_typeahead = ["tab"]
trigger_labels = "lalt"
next = ["down"]
prev = ["up"]
close = ["esc"]
remove_from_history = ["shift backspace"]
resume_query = ["ctrl r"]
toggle_exact_search = ["ctrl m"]

[keys.activation_modifiers]
keep_open = "shift"
alternate = "alt"

[keys.ai]
clear_session = ["ctrl x"]
copy_last_response = ["ctrl c"]
resume_session = ["ctrl r"]
run_last_response = ["ctrl e"]

[events]
on_activate = ""
on_selection = ""
on_exit = ""
on_launch = ""
on_query_change = ""

[list]
dynamic_sub = true
keyboard_scroll_style = "emacs"
max_entries = 50
show_initial_entries = true
single_click = true
visibility_threshold = 20
placeholder = "No Results"

[search]
argument_delimiter = "#"
placeholder = "Search..."
delay = 0
resume_last_query = false

[activation_mode]
labels = "jkl;asdf"

[builtins.applications]
weight = 5
name = "applications"
placeholder = "Applications"
prioritize_new = true
hide_actions_with_empty_query = true
context_aware = true
refresh = true
show_sub_when_single = true
show_icon_when_single = true
show_generic = true
history = true

[builtins.applications.actions]
enabled = true
hide_category = false
hide_without_query = true

[builtins.bookmarks]
weight = 5
placeholder = "Bookmarks"
name = "bookmarks"
icon = "bookmark"
switcher_only = true

[[builtins.bookmarks.entries]]
label = "Walker"
url = "https://github.com/abenz1267/walker"
keywords = ["walker", "github"]

[builtins.xdph_picker]
hidden = true
weight = 5
placeholder = "Screen/Window Picker"
show_sub_when_single = true
name = "xdphpicker"
switcher_only = true

[builtins.ai]
weight = 5
placeholder = "AI"
name = "ai"
icon = "help-browser"
switcher_only = true

[[builtins.ai.anthropic.prompts]]
model = "claude-3-5-sonnet-20241022"
temperature = 1
max_tokens = 1_000
label = "General Assistant"
prompt = "You are a helpful general assistant. Keep your answers short and precise."

[builtins.calc]
require_number = true
weight = 5
name = "calc"
icon = "accessories-calculator"
placeholder = "Calculator"
min_chars = 4

[builtins.windows]
weight = 5
icon = "view-restore"
name = "windows"
placeholder = "Windows"
show_icon_when_single = true

[builtins.clipboard]
exec = "wl-copy"
weight = 5
name = "clipboard"
avoid_line_breaks = true
placeholder = "Clipboard"
image_height = 300
max_entries = 10
switcher_only = true

[builtins.commands]
weight = 5
icon = "utilities-terminal"
switcher_only = true
name = "commands"
placeholder = "Commands"

[builtins.custom_commands]
weight = 5
icon = "utilities-terminal"
name = "custom_commands"
placeholder = "Custom Commands"

[builtins.emojis]
exec = "wl-copy"
weight = 5
name = "emojis"
placeholder = "Emojis"
switcher_only = true
history = true
typeahead = true
show_unqualified = false

[builtins.symbols]
after_copy = ""
weight = 5
name = "symbols"
placeholder = "Symbols"
switcher_only = true
history = true
typeahead = true

[builtins.finder]
use_fd = false
weight = 5
icon = "file"
name = "finder"
placeholder = "Finder"
switcher_only = true
ignore_gitignore = true
refresh = true
concurrency = 8
show_icon_when_single = true

[builtins.runner]
weight = 5
icon = "utilities-terminal"
name = "runner"
placeholder = "Runner"
typeahead = true
history = true
generic_entry = false
refresh = true

[builtins.ssh]
weight = 5
icon = "preferences-system-network"
name = "ssh"
placeholder = "SSH"
switcher_only = true
history = true
refresh = true

[builtins.switcher]
weight = 5
name = "switcher"
placeholder = "Switcher"
prefix = "/"

[builtins.websearch]
weight = 5
icon = "applications-internet"
name = "websearch"
placeholder = "Websearch"

[[builtins.websearch.entries]]
name = "Google"
url = "https://www.google.com/search?q=%TERM%"

[[builtins.websearch.entries]]
name = "DuckDuckGo"
url = "https://duckduckgo.com/?q=%TERM%"
switcher_only = true

[[builtins.websearch.entries]]
name = "Ecosia"
url = "https://www.ecosia.org/search?q=%TERM%"
switcher_only = true

[[builtins.websearch.entries]]
name = "Yandex"
url = "https://yandex.com/search/?text=%TERM%"
switcher_only = true

[builtins.dmenu]
hidden = true
weight = 5
name = "dmenu"
placeholder = "Dmenu"
switcher_only = true
```

**Desktop**

- NixOS (Linux)
- Hyprland

**Logs**

```
=6 code_file=../gdk/gdkvulkancontext.c code_line=1650 code_func=gdk_vulkan_debug_report glib_domain=Gdk
**
Gtk:ERROR:../gtk/gtkwindow.c:4991:check_crossing_invariants: assertion failed: (crossing->new_target == crossing->new_descendent || gtk_widget_is_ancestor (crossing->new_target, crossing->new_descendent))
Bail out! Gtk:ERROR:../gtk/gtkwindow.c:4991:check_crossing_invariants: assertion failed: (crossing->new_target == crossing->new_descendent || gtk_widget_is_ancestor (crossing->new_target, crossing->new_descendent))
SIGABRT: abort
PC=0x7fbc674988ec m=0 sigcode=18446744073709551610
signal arrived during cgo execution

goroutine 1 gp=0xc0000061c0 m=0 mp=0x1825920 [syscall, locked to thread]:
runtime.cgocall(0xaf92f0, 0xc0004c3b00)
        runtime/cgocall.go:167 +0x4b fp=0xc0004c3ad8 sp=0xc0004c3aa0 pc=0x55b1ab
github.com/diamondburned/gotk4/pkg/gio/v2._Cfunc_g_application_run(0x223d70e0, 0x1, 0x22420240)
        _cgo_gotypes.go:14100 +0x4b fp=0xc0004c3b00 sp=0xc0004c3ad8 pc=0x74e00b
github.com/diamondburned/gotk4/pkg/gio/v2.(*Application).Run.func3(0x223d70e0, 0x1, 0x22420240)
        github.com/diamondburned/gotk4/pkg@v0.3.1/gio/v2/gio.go:42200 +0x67 fp=0xc0004c3b30 sp=0xc0004c3b00 pc=0x76de27
github.com/diamondburned/gotk4/pkg/gio/v2.(*Application).Run(0xc0002a4000, {0xc0000241b0, 0x1, 0x1})
        github.com/diamondburned/gotk4/pkg@v0.3.1/gio/v2/gio.go:42200 +0x1f1 fp=0xc0004c3bd8 sp=0xc0004c3b30 pc=0x76dd11
main.main()
        ./walker.go:312 +0x90d fp=0xc0004c3f50 sp=0xc0004c3bd8 pc=0xadd42d
runtime.main()
        runtime/proc.go:272 +0x28b fp=0xc0004c3fe0 sp=0xc0004c3f50 pc=0x52cc8b
runtime.goexit({})
        runtime/asm_amd64.s:1700 +0x1 fp=0xc0004c3fe8 sp=0xc0004c3fe0 pc=0x569aa1

goroutine 17 gp=0xc000006700 m=1 mp=0xc000082008 [syscall, locked to thread]:
runtime.goexit({})
        runtime/asm_amd64.s:1700 +0x1 fp=0xc000092fe8 sp=0xc000092fe0 pc=0x569aa1

goroutine 2 gp=0xc000006c40 m=nil [force gc (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
        runtime/proc.go:424 +0xce fp=0xc00007cfa8 sp=0xc00007cf88 pc=0x56162e
runtime.goparkunlock(...)
        runtime/proc.go:430
runtime.forcegchelper()
        runtime/proc.go:337 +0xb3 fp=0xc00007cfe0 sp=0xc00007cfa8 pc=0x52cfd3
runtime.goexit({})
        runtime/asm_amd64.s:1700 +0x1 fp=0xc00007cfe8 sp=0xc00007cfe0 pc=0x569aa1
created by runtime.init.7 in goroutine 1
        runtime/proc.go:325 +0x1a

goroutine 3 gp=0xc000007180 m=nil [GC sweep wait]:
runtime.gopark(0x1?, 0x0?, 0x0?, 0x0?, 0x0?)
        runtime/proc.go:424 +0xce fp=0xc00007d780 sp=0xc00007d760 pc=0x56162e
runtime.goparkunlock(...)
        runtime/proc.go:430
runtime.bgsweep(0xc000032080)
        runtime/mgcsweep.go:317 +0xdf fp=0xc00007d7c8 sp=0xc00007d780 pc=0x514c9f
runtime.gcenable.gowrap1()
        runtime/mgc.go:204 +0x25 fp=0xc00007d7e0 sp=0xc00007d7c8 pc=0x509365
runtime.goexit({})
        runtime/asm_amd64.s:1700 +0x1 fp=0xc00007d7e8 sp=0xc00007d7e0 pc=0x569aa1
created by runtime.gcenable in goroutine 1
        runtime/mgc.go:204 +0x66

goroutine 4 gp=0xc000007340 m=nil [GC scavenge wait]:
runtime.gopark(0x10000?, 0x11d6520?, 0x0?, 0x0?, 0x0?)
        runtime/proc.go:424 +0xce fp=0xc00007df78 sp=0xc00007df58 pc=0x56162e
runtime.goparkunlock(...)
        runtime/proc.go:430
runtime.(*scavengerState).park(0x1823f40)
        runtime/mgcscavenge.go:425 +0x49 fp=0xc00007dfa8 sp=0xc00007df78 pc=0x512689
runtime.bgscavenge(0xc000032080)
        runtime/mgcscavenge.go:658 +0x59 fp=0xc00007dfc8 sp=0xc00007dfa8 pc=0x512c19
runtime.gcenable.gowrap2()
        runtime/mgc.go:205 +0x25 fp=0xc00007dfe0 sp=0xc00007dfc8 pc=0x509305
runtime.goexit({})
        runtime/asm_amd64.s:1700 +0x1 fp=0xc00007dfe8 sp=0xc00007dfe0 pc=0x569aa1
created by runtime.gcenable in goroutine 1
        runtime/mgc.go:205 +0xa5

goroutine 5 gp=0xc000007c00 m=nil [finalizer wait]:
runtime.gopark(0x0?, 0x112a260?, 0x90?, 0xc6?, 0x1000000010?)
        runtime/proc.go:424 +0xce fp=0xc00007c620 sp=0xc00007c600 pc=0x56162e
runtime.runfinq()
        runtime/mfinal.go:193 +0x107 fp=0xc00007c7e0 sp=0xc00007c620 pc=0x508367
runtime.goexit({})
        runtime/asm_amd64.s:1700 +0x1 fp=0xc00007c7e8 sp=0xc00007c7e0 pc=0x569aa1
created by runtime.createfing in goroutine 1
        runtime/mfinal.go:163 +0x3d

goroutine 6 gp=0xc000230000 m=nil [chan receive]:
runtime.gopark(0xc00007e760?, 0x6b9ae5?, 0x70?, 0xf4?, 0x11f6d20?)
        runtime/proc.go:424 +0xce fp=0xc00007e718 sp=0xc00007e6f8 pc=0x56162e
runtime.chanrecv(0xc0000405b0, 0x0, 0x1)
        runtime/chan.go:639 +0x41c fp=0xc00007e790 sp=0xc00007e718 pc=0x4f8ebc
runtime.chanrecv1(0x0?, 0x0?)
        runtime/chan.go:489 +0x12 fp=0xc00007e7b8 sp=0xc00007e790 pc=0x4f8a72
runtime.unique_runtime_registerUniqueMapCleanup.func1(...)
        runtime/mgc.go:1781
runtime.unique_runtime_registerUniqueMapCleanup.gowrap1()
        runtime/mgc.go:1784 +0x2f fp=0xc00007e7e0 sp=0xc00007e7b8 pc=0x50c38f
runtime.goexit({})
        runtime/asm_amd64.s:1700 +0x1 fp=0xc00007e7e8 sp=0xc00007e7e0 pc=0x569aa1
created by unique.runtime_registerUniqueMapCleanup in goroutine 1
        runtime/mgc.go:1779 +0x96

goroutine 7 gp=0xc0002a6000 m=nil [GC worker (idle)]:
runtime.gopark(0xc00002ee01?, 0xc0001facd0?, 0xa8?, 0x87?, 0x5edaf5?)
        runtime/proc.go:424 +0xce fp=0xc000078738 sp=0xc000078718 pc=0x56162e
runtime.gcBgMarkWorker(0xc0002a9650)
        runtime/mgc.go:1412 +0xe9 fp=0xc0000787c8 sp=0xc000078738 pc=0x50b6a9
runtime.gcBgMarkStartWorkers.gowrap1()
        runtime/mgc.go:1328 +0x25 fp=0xc0000787e0 sp=0xc0000787c8 pc=0x50b585
runtime.goexit({})
        runtime/asm_amd64.s:1700 +0x1 fp=0xc0000787e8 sp=0xc0000787e0 pc=0x569aa1
created by runtime.gcBgMarkStartWorkers in goroutine 1
        runtime/mgc.go:1328 +0x105

goroutine 19 gp=0xc0002a68c0 m=nil [GC worker (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
        runtime/proc.go:424 +0xce fp=0xc000078f38 sp=0xc000078f18 pc=0x56162e
runtime.gcBgMarkWorker(0xc0002a9650)
        runtime/mgc.go:1412 +0xe9 fp=0xc000078fc8 sp=0xc000078f38 pc=0x50b6a9
runtime.gcBgMarkStartWorkers.gowrap1()
        runtime/mgc.go:1328 +0x25 fp=0xc000078fe0 sp=0xc000078fc8 pc=0x50b585
runtime.goexit({})
        runtime/asm_amd64.s:1700 +0x1 fp=0xc000078fe8 sp=0xc000078fe0 pc=0x569aa1
created by runtime.gcBgMarkStartWorkers in goroutine 1
        runtime/mgc.go:1328 +0x105

goroutine 8 gp=0xc000230700 m=nil [GC worker (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
        runtime/proc.go:424 +0xce fp=0xc00007ef38 sp=0xc00007ef18 pc=0x56162e
runtime.gcBgMarkWorker(0xc0002a9650)
        runtime/mgc.go:1412 +0xe9 fp=0xc00007efc8 sp=0xc00007ef38 pc=0x50b6a9
runtime.gcBgMarkStartWorkers.gowrap1()
        runtime/mgc.go:1328 +0x25 fp=0xc00007efe0 sp=0xc00007efc8 pc=0x50b585
runtime.goexit({})
        runtime/asm_amd64.s:1700 +0x1 fp=0xc00007efe8 sp=0xc00007efe0 pc=0x569aa1
created by runtime.gcBgMarkStartWorkers in goroutine 1
        runtime/mgc.go:1328 +0x105

goroutine 9 gp=0xc0002308c0 m=nil [GC worker (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
        runtime/proc.go:424 +0xce fp=0xc00007f738 sp=0xc00007f718 pc=0x56162e
runtime.gcBgMarkWorker(0xc0002a9650)
        runtime/mgc.go:1412 +0xe9 fp=0xc00007f7c8 sp=0xc00007f738 pc=0x50b6a9
runtime.gcBgMarkStartWorkers.gowrap1()
        runtime/mgc.go:1328 +0x25 fp=0xc00007f7e0 sp=0xc00007f7c8 pc=0x50b585
runtime.goexit({})
        runtime/asm_amd64.s:1700 +0x1 fp=0xc00007f7e8 sp=0xc00007f7e0 pc=0x569aa1
created by runtime.gcBgMarkStartWorkers in goroutine 1
        runtime/mgc.go:1328 +0x105

goroutine 10 gp=0xc000230a80 m=nil [GC worker (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
        runtime/proc.go:424 +0xce fp=0xc00007ff38 sp=0xc00007ff18 pc=0x56162e
runtime.gcBgMarkWorker(0xc0002a9650)
        runtime/mgc.go:1412 +0xe9 fp=0xc00007ffc8 sp=0xc00007ff38 pc=0x50b6a9
runtime.gcBgMarkStartWorkers.gowrap1()
        runtime/mgc.go:1328 +0x25 fp=0xc00007ffe0 sp=0xc00007ffc8 pc=0x50b585
runtime.goexit({})
        runtime/asm_amd64.s:1700 +0x1 fp=0xc00007ffe8 sp=0xc00007ffe0 pc=0x569aa1
created by runtime.gcBgMarkStartWorkers in goroutine 1
        runtime/mgc.go:1328 +0x105

goroutine 35 gp=0xc000104380 m=nil [GC worker (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
        runtime/proc.go:424 +0xce fp=0xc00011c738 sp=0xc00011c718 pc=0x56162e
runtime.gcBgMarkWorker(0xc0002a9650)
        runtime/mgc.go:1412 +0xe9 fp=0xc00011c7c8 sp=0xc00011c738 pc=0x50b6a9
runtime.gcBgMarkStartWorkers.gowrap1()
        runtime/mgc.go:1328 +0x25 fp=0xc00011c7e0 sp=0xc00011c7c8 pc=0x50b585
runtime.goexit({})
        runtime/asm_amd64.s:1700 +0x1 fp=0xc00011c7e8 sp=0xc00011c7e0 pc=0x569aa1
created by runtime.gcBgMarkStartWorkers in goroutine 1
        runtime/mgc.go:1328 +0x105

goroutine 20 gp=0xc0002a6a80 m=nil [GC worker (idle)]:
runtime.gopark(0x188180e1e647?, 0x0?, 0x0?, 0x0?, 0x0?)
        runtime/proc.go:424 +0xce fp=0xc000079738 sp=0xc000079718 pc=0x56162e
runtime.gcBgMarkWorker(0xc0002a9650)
        runtime/mgc.go:1412 +0xe9 fp=0xc0000797c8 sp=0xc000079738 pc=0x50b6a9
runtime.gcBgMarkStartWorkers.gowrap1()
        runtime/mgc.go:1328 +0x25 fp=0xc0000797e0 sp=0xc0000797c8 pc=0x50b585
runtime.goexit({})
        runtime/asm_amd64.s:1700 +0x1 fp=0xc0000797e8 sp=0xc0000797e0 pc=0x569aa1
created by runtime.gcBgMarkStartWorkers in goroutine 1
        runtime/mgc.go:1328 +0x105

goroutine 11 gp=0xc000230fc0 m=nil [GC worker (idle)]:
runtime.gopark(0x188180e1ebd7?, 0x0?, 0x0?, 0x0?, 0x0?)
        runtime/proc.go:424 +0xce fp=0xc000118738 sp=0xc000118718 pc=0x56162e
runtime.gcBgMarkWorker(0xc0002a9650)
        runtime/mgc.go:1412 +0xe9 fp=0xc0001187c8 sp=0xc000118738 pc=0x50b6a9
runtime.gcBgMarkStartWorkers.gowrap1()
        runtime/mgc.go:1328 +0x25 fp=0xc0001187e0 sp=0xc0001187c8 pc=0x50b585
runtime.goexit({})
        runtime/asm_amd64.s:1700 +0x1 fp=0xc0001187e8 sp=0xc0001187e0 pc=0x569aa1
created by runtime.gcBgMarkStartWorkers in goroutine 1
        runtime/mgc.go:1328 +0x105

goroutine 13 gp=0xc000231340 m=nil [select]:
runtime.gopark(0xc000090f78?, 0x2?, 0xdd?, 0xc2?, 0xc000090f0c?)
        runtime/proc.go:424 +0xce fp=0xc000090db0 sp=0xc000090d90 pc=0x56162e
runtime.selectgo(0xc000090f78, 0xc000090f08, 0xc00028b920?, 0x0, 0x0?, 0x1)
        runtime/select.go:335 +0x7a5 fp=0xc000090ed8 sp=0xc000090db0 pc=0x53ed05
github.com/abenz1267/walker/internal/modules.(*Applications).RunWm(0xc000198000)
        github.com/abenz1267/walker/internal/modules/applications.go:136 +0x13c fp=0xc000090fc8 sp=0xc000090ed8 pc=0xa77e3c
github.com/abenz1267/walker/internal/modules.(*Applications).SetupData.gowrap2()
        github.com/abenz1267/walker/internal/modules/applications.go:63 +0x25 fp=0xc000090fe0 sp=0xc000090fc8 pc=0xa77725
runtime.goexit({})
        runtime/asm_amd64.s:1700 +0x1 fp=0xc000090fe8 sp=0xc000090fe0 pc=0x569aa1
created by github.com/abenz1267/walker/internal/modules.(*Applications).SetupData in goroutine 12
        github.com/abenz1267/walker/internal/modules/applications.go:63 +0xf8

goroutine 21 gp=0xc000231500 m=nil [IO wait]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
        runtime/proc.go:424 +0xce fp=0xc000342b10 sp=0xc000342af0 pc=0x56162e
runtime.netpollblock(0x0?, 0x4f62c6?, 0x0?)
        runtime/netpoll.go:575 +0xf7 fp=0xc000342b48 sp=0xc000342b10 pc=0x525617
internal/poll.runtime_pollWait(0x7fbc1c08ef50, 0x72)
        runtime/netpoll.go:351 +0x85 fp=0xc000342b68 sp=0xc000342b48 pc=0x560925
internal/poll.(*pollDesc).wait(0xc000346000?, 0xc000352000?, 0x0)
        internal/poll/fd_poll_runtime.go:84 +0x27 fp=0xc000342b90 sp=0xc000342b68 pc=0x5c5767
internal/poll.(*pollDesc).waitRead(...)
        internal/poll/fd_poll_runtime.go:89
internal/poll.(*FD).ReadMsg(0xc000346000, {0xc000352000, 0x8, 0x60}, {0xc00035e000, 0x18, 0x78}, 0x40000000)
        internal/poll/fd_unix.go:302 +0x385 fp=0xc000342c78 sp=0xc000342b90 pc=0x5c6965
net.(*netFD).readMsg(0xc000346000, {0xc000352000?, 0x4?, 0x55fb94?}, {0xc00035e000?, 0x0?, 0xc000342dd0?}, 0x55c2dd?)
        net/fd_posix.go:78 +0x31 fp=0xc000342d00 sp=0xc000342c78 pc=0x6cd831
net.(*UnixConn).readMsg(0xc000080000, {0xc000352000?, 0xbf0340?, 0x2?}, {0xc00035e000?, 0xc000342df8?, 0xa5a1de?})
        net/unixsock_posix.go:115 +0x45 fp=0xc000342d90 sp=0xc000342d00 pc=0x6e14c5
net.(*UnixConn).ReadMsgUnix(0xc000080000, {0xc000352000?, 0xc0002a5710?, 0xc0000bf710?}, {0xc00035e000?, 0x55c2dd?, 0x2a?})
        net/unixsock.go:143 +0x36 fp=0xc000342e08 sp=0xc000342d90 pc=0x6e00b6
github.com/neurlang/wayland/wl.(*Context).readEvent(0xc0000e8230)
        github.com/neurlang/wayland@v0.1.36/wl/event.go:49 +0xa9 fp=0xc000342f00 sp=0xc000342e08 pc=0xa58869
github.com/neurlang/wayland/wl.(*Context).run(0xc0000e8230, 0x0)
        github.com/neurlang/wayland@v0.1.36/wl/context.go:165 +0x2d fp=0xc000342f78 sp=0xc000342f00 pc=0xa582ad
github.com/neurlang/wayland/wl.(*Context).Run(...)
        github.com/neurlang/wayland@v0.1.36/wl/context.go:147
github.com/abenz1267/walker/internal/modules/windows/wlr.StartWM(0x0?, 0xdca7a5?)
        github.com/abenz1267/walker/internal/modules/windows/wlr/wm.go:64 +0x17e fp=0xc000342fc0 sp=0xc000342f78 pc=0xa5cc7e
github.com/abenz1267/walker/internal/modules.(*Applications).RunWm.gowrap1()
        github.com/abenz1267/walker/internal/modules/applications.go:133 +0x25 fp=0xc000342fe0 sp=0xc000342fc0 pc=0xa781e5
runtime.goexit({})
        runtime/asm_amd64.s:1700 +0x1 fp=0xc000342fe8 sp=0xc000342fe0 pc=0x569aa1
created by github.com/abenz1267/walker/internal/modules.(*Applications).RunWm in goroutine 13
        github.com/abenz1267/walker/internal/modules/applications.go:133 +0xb7

rax    0x0
rbx    0x8e4ae
rcx    0x7fbc674988ec
rdx    0x6
rdi    0x8e4ae
rsi    0x8e4ae
rbp    0x7fbc63b58bc0
rsp    0x7ffd31637a20
r8     0x0
r9     0x0
r10    0x8
r11    0x246
r12    0x7fbc6899ade0
r13    0x6
r14    0x7ffd31637b30
r15    0x2
rip    0x7fbc674988ec
rflags 0x246
cs     0x33
fs     0x0
gs     0x0
```
