### ISSUE TITLE
How to target walker window in xremap?

### ISSUE THREAD

**Issue by kohane27** [abenz1267/walker#273]
Hello. Hope you're doing well.

Thank you so much for this Wayland native launcher. It's closest to what I want.

I'm trying to target the walker window because I need to remap `ctrl-w` to be `ctrl-backspace` and `ctrl-h` to be `backspace`:

```
  - name: walker
    application:
      only: [walker]
    remap:
      CTRL-KEY_W: CTRL-KEY_BACKSPACE
      CTRL-KEY_H: KEY_BACKSPACE
```

However, when I run `hyprctl clients -j`, I could not find any walker info.

Any help is much appreciated. Thank you!
