### ISSUE TITLE
Some .desktop entries don't get shown in list

### ISSUE THREAD

**Issue by Zakar98k** [abenz1267/walker#313]
**Describe the bug**
There are some missing .desktop entries in walker that are present when using other launchers like anyrun. Namely Librewolf and a few others, even though their .desktop entry is present in ~/.local/share/applications or /usr/share/applications

**Version**
0.12.21

**Minimal Config**
Here is my applications config
```toml
[builtins.applications]
cache = true
weight = 5
eager_loading = true
name = "applications"
placeholder = "Applications"
prioritize_new = true
hide_actions_with_empty_query = false
context_aware = true
refresh = true
show_sub_when_single = true
show_icon_when_single = true
show_generic = true

[builtins.applications.actions]
enabled = false
hide_category = false
hide_without_query = false
```

**To Reproduce**
- `walker --new --modules applications`
- search for app
- app is missing from list

**Expected behavior**
- `walker --new --modules applications`
- search for app
- app is listed and able to be launched 

**Screenshots**
Walker:
![Image](https://github.com/user-attachments/assets/70f1a2da-2869-4d1c-92ce-172a40af2194)

Anyrun: 

![Image](https://github.com/user-attachments/assets/9fd720f6-26f4-439f-8281-2d815234c71a)

**Desktop**

- OS (EndeavorOS)
- DE (Niri)

**Additional context**
