### ISSUE TITLE
Sending more than 1 query param in websearch entries doesn't work

### ISSUE THREAD

**Issue by karamanliev** [abenz1267/walker#332]
**Describe the bug**
When using more query params with `&` text after it gets cut off when sent to the browser. For example using this:
```toml
[[builtins.websearch.entries]]
name = "DuckDuckGo"
url = "https://duckduckgo.com/?queryParam1=something&queryParam2=somethingElse&queryParam3=%TERM%"
```
What is actually send to the browser is `https://duckduckgo.com/?queryParam1=something` and is missing `queryParam2` and `queryParam3`

**Version**
0.12.23

**Expected behavior**
The full url `https://duckduckgo.com/?queryParam1=something&queryParam2=somethingElse&queryParam3=%TERM%` should be sent to the browser.

**Desktop**

- Arch Linux
- Hyprland
